# PIO — Adu Arsitektur: bisakah model lain mengalahkan **YOLOv10n/s/m**?

Lanjutan dari notebook replikasi PIO. Di sini kita **membandingkan beberapa arsitektur deteksi pada dataset & epoch yang sama** untuk melihat mana yang mengungguli YOLOv10 yang dipakai paper.

## Rekomendasi & alasan
| Arsitektur | Tahun | Kenapa berpeluang mengalahkan YOLOv10 |
|---|---|---|
| **YOLO11** (n/s/m) | 2024 | Penerus langsung YOLOv10 (Ultralytics). Backbone **C3k2** + blok atensi **C2PSA** → mAP lebih tinggi pada ukuran setara, parameter lebih sedikit. **Paling andal** menang pada epoch sama. |
| **YOLOv12** (n/s/m) | 2025 | Berbasis **atensi** (area-attention, R-ELAN). Sering mengungguli YOLO11 pada mAP; cocok untuk scene **padat/oklusi** seperti kandang ayam. Lebih berat/lambat. |
| **YOLOv9** (t/s/m) | 2024 | **PGI + GELAN** mengurangi kehilangan informasi → kuat pada objek kecil. Pesaing tangguh. |
| **YOLOv8** (n/s/m) | 2023 | Baseline matang & stabil; pembanding "generasi sebelumnya". |
| **YOLOv10** (n/s/m) | 2024 | **Baseline paper** (NMS-free, dual assignment). Dilatih ulang di sini agar adil (epoch sama). |

> **Adu adil.** Untuk tiap *tier* (n/s/m), **semua** arsitektur memakai resep **identik dari Tabel 7 paper**: n/s → 640px, lr0 0.002, batch 4; m → 960px, lr0 0.02, batch 2; AdamW, momentum 0.9, **epoch sama**, seed sama. Tidak ada tuning per-model → perbedaan murni dari arsitektur.

> **RT-DETR (transformer)** sengaja tidak dimasukkan default: konvergensinya lambat, pada epoch sedikit hampir pasti kalah. Bisa ditambah bila mau latih lama.

> ⚠️ **Waktu.** Default = 5 keluarga × 3 tier = **15 training**. Pada Colab T4 ini lama walau hanya 3 epoch. **Pangkas `FAMILIES`/`TIERS`** atau jalankan bertahap. Untuk angka "sebenarnya", naikkan epoch (mahal).

## 0 · Setup (sama seperti notebook replikasi, Ultralytics 8.3.152 utk keadilan)

In [31]:
!nvidia-smi --query-gpu=name,memory.total --format=csv 2>/dev/null || echo "Aktifkan GPU"
%pip install -q "ultralytics==8.3.152" requests tqdm rarfile pandas
!apt-get -qq install -y unrar >/dev/null 2>&1 || true
!apt-get -qq install -y p7zip-full unar >/dev/null 2>&1 || true
import os, random, glob, re, collections, shutil, subprocess, zipfile
import numpy as np, pandas as pd
import ultralytics, torch
ultralytics.checks()
SEED=0
os.environ["PYTHONHASHSEED"]=str(SEED); random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)
print("ultralytics", ultralytics.__version__, "| CUDA", torch.cuda.is_available())

Ultralytics 8.3.152  Python-3.11.9 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32607MiB)
Setup complete  (32 CPUs, 63.8 GB RAM, 365.2/3906.2 GB disk)
ultralytics 8.3.152 | CUDA True

## 1 · Data (pakai ulang dataset PIO di Drive-mu)

Sama seperti notebook utama: mount Drive, lewati unduh bila `data.rar` sudah ada, ekstrak ke disk lokal, lalu bangun split + `dataset.yaml`. Jika kamu sudah menjalankan notebook utama, `data.rar` sudah di `MyDrive/PIO/downloads` → bagian ini cepat.

In [32]:
from pathlib import Path
import os

# Folder tempat notebook berada
BASE = Path.cwd()

# Ganti bila folder hasil ekstrakmu berada di lokasi lain
DATA_ROOT = BASE / "downloads" / "data"

# Folder output training, CSV, grafik, dan bobot model
RUNS_DIR = BASE / "runs_compare"

# Tidak dipakai untuk download, tapi dibiarkan supaya kompatibel dengan cell lain
DL_DIR = BASE / "downloads"

for folder in [DL_DIR, RUNS_DIR, DATA_ROOT]:
    folder.mkdir(parents=True, exist_ok=True)

print("Project root :", BASE)
print("Dataset     :", DATA_ROOT)
print("Output run  :", RUNS_DIR)

Project root : e:\CCTV\PIO
Dataset     : e:\CCTV\PIO\downloads\data
Output run  : e:\CCTV\PIO\runs_compare

In [33]:
import glob

IMG_EXT = (".jpg", ".jpeg", ".png", ".bmp")

images = [
    p for p in glob.glob(
        os.path.join(str(DATA_ROOT), "**", "*"),
        recursive=True
    )
    if p.lower().endswith(IMG_EXT)
]

labels = glob.glob(
    os.path.join(str(DATA_ROOT), "**", "*.txt"),
    recursive=True
)

print("Jumlah gambar :", len(images))
print("Jumlah label  :", len(labels))

if len(images) == 0:
    raise FileNotFoundError(
        f"Tidak menemukan gambar di folder dataset: {DATA_ROOT}"
    )

if len(labels) == 0:
    raise FileNotFoundError(
        f"Tidak menemukan file label .txt di folder dataset: {DATA_ROOT}"
    )

print("✓ Dataset lokal terdeteksi dan siap diproses.")

Jumlah gambar : 1487
Jumlah label  : 1489
✓ Dataset lokal terdeteksi dan siap diproses.

In [34]:
# Bangun split (pakai split bawaan data.rar bila ada) + dataset.yaml + struktur symlink lokal
import yaml
IMG_EXT=(".jpg",".jpeg",".png",".bmp")
def find_split_dirs(root):
    f={}
    for s in ("train","val","valid"):
        for d in glob.glob(os.path.join(root,"**","images",s),recursive=True): f.setdefault(("images","val" if s.startswith("val") else "train"),d)
        for d in glob.glob(os.path.join(root,"**","labels",s),recursive=True): f.setdefault(("labels","val" if s.startswith("val") else "train"),d)
    return f
def all_images(root): return sorted(p for p in glob.glob(os.path.join(root,"**","*"),recursive=True) if p.lower().endswith(IMG_EXT))
def label_for(img):
    stem=os.path.splitext(os.path.basename(img))[0]
    cand=os.path.splitext(img.replace(os.sep+"images"+os.sep,os.sep+"labels"+os.sep))[0]+".txt"
    if os.path.exists(cand): return cand
    h=glob.glob(os.path.join(DATA_ROOT,"**",stem+".txt"),recursive=True); return h[0] if h else None
def parse_house(name):
    b=os.path.basename(name); m=re.search(r"(?i)(?:^|[_\-])([CP])-?W[-_ ]?[1-6]",b)
    return {"c":"Commercial","p":"Prototype"}[m.group(1).lower()] if m else "Unknown"
def parse_week(name):
    m=re.search(r"(?i)[-_ ]W[-_ ]?([1-6])\b",os.path.basename(name)); return f"W{m.group(1)}" if m else "W?"

splits=find_split_dirs(DATA_ROOT)
PREMADE=("images","train") in splits and ("images","val") in splits
recs=[]
if PREMADE:
    for sp in ("train","val"):
        for img in all_images(splits[("images",sp)]): recs.append([img,label_for(img),sp])
else:
    pairs=[(i,label_for(i)) for i in all_images(DATA_ROOT)]; pairs=[(i,l) for i,l in pairs if l]
    rng=random.Random(SEED); st=collections.defaultdict(list)
    for i,l in pairs: st[(parse_house(i),parse_week(i))].append((i,l))
    for items in st.values():
        items=sorted(items); rng.shuffle(items); nval=round(len(items)*0.3)
        for idx,(i,l) in enumerate(items): recs.append([i,l,"val" if idx<nval else "train"])
df=pd.DataFrame(recs,columns=["img","lbl","split"])
print("Split:","BAWAAN" if PREMADE else "70/30 dibuat","| train",(df.split=="train").sum(),"| val",(df.split=="val").sum())

NORM = str(BASE / "_pio_yolo")
shutil.rmtree(NORM, ignore_errors=True)
for sub in ["images/train","images/val","labels/train","labels/val"]: os.makedirs(os.path.join(NORM,sub),exist_ok=True)
def link(s,d):
    if os.path.lexists(d): return
    try: os.symlink(os.path.abspath(s),d)
    except Exception: shutil.copy(s,d)
for r in df.itertuples():
    if not r.lbl: continue
    base=os.path.basename(r.img); stem=os.path.splitext(base)[0]
    link(r.img,os.path.join(NORM,"images",r.split,base)); link(r.lbl,os.path.join(NORM,"labels",r.split,stem+".txt"))
YAML_PATH=os.path.join(NORM,"dataset.yaml")
yaml.safe_dump({"path":NORM,"train":"images/train","val":"images/val","nc":1,"names":["pollo"]},open(YAML_PATH,"w"),sort_keys=False)
print("dataset.yaml siap:",YAML_PATH)

Split: BAWAAN | train 1035 | val 452
dataset.yaml siap: e:\CCTV\PIO\_pio_yolo\dataset.yaml

## 2 · Model zoo & konfigurasi adu

Edit `FAMILIES` / `TIERS` untuk memangkas. Resep per-tier diambil **persis** dari Tabel 7.

In [35]:
# Keluarga arsitektur & tier yang diadu (pangkas utk hemat waktu)
FAMILIES = ["yolo11"]   # yolov10 = baseline paper
TIERS    = ["m"]
QUICK_TEST = False                  # True=3 epoch (demo). False=epoch penuh (mahal).
EPOCHS   = 1 if QUICK_TEST else 100

# Resep PERSIS Tabel 7 — dipakai sama utk SEMUA arsitektur di tier itu (adu adil)
TIER_CFG = {
    "n": dict(imgsz=640, lr0=0.002, batch=4, optimizer="AdamW", momentum=0.9),
    "s": dict(imgsz=640, lr0=0.002, batch=4, optimizer="AdamW", momentum=0.9),
    "m": dict(imgsz=960, lr0=0.02,  batch=2, optimizer="AdamW", momentum=0.9),
}

def weight_name(family, tier):
    "Penamaan bobot Ultralytics (tak seragam antar versi)."
    if family == "yolov9":                       # v9: t/s/m (bukan n)
        return "yolov9" + {"n":"t","s":"s","m":"m"}[tier] + ".pt"
    return f"{family}{tier}.pt"                   # v8/v10 pakai 'v'; 11/12 tanpa 'v'

MODELS = []
for tier in TIERS:
    for fam in FAMILIES:
        w = weight_name(fam, tier)
        MODELS.append(dict(label=os.path.splitext(w)[0], family=fam, tier=tier, weight=w))
print(f"{len(MODELS)} model akan dilatih (epoch={EPOCHS}):")
for m in MODELS: print(f"  {m['label']:<12} tier={m['tier']}  ({m['weight']})")

1 model akan dilatih (epoch=100):
  yolo11m      tier=m  (yolo11m.pt)

## 3 · Training (semua model, resep identik per tier)

Tiap model gagal-load/gagal-latih dilewati dengan pesan (tidak menghentikan keseluruhan).

In [36]:
from ultralytics import YOLO
import time
trained = {}
for m in MODELS:
    c = TIER_CFG[m["tier"]]; runname = "cmp_" + m["label"]
    print(f"\n===== {m['label']} (tier {m['tier']}: imgsz={c['imgsz']} lr0={c['lr0']} batch={c['batch']} epochs={EPOCHS}) =====")
    try:
        model = YOLO(m["weight"])
    except Exception as e:
        print("  ! gagal load", m["weight"], "->", e, "(dilewati; mungkin butuh ultralytics lebih baru)"); continue
    try:
        t0 = time.time()
        model.train(data=YAML_PATH, epochs=EPOCHS, imgsz=c["imgsz"], batch=c["batch"],
                    optimizer=c["optimizer"], lr0=c["lr0"], momentum=c["momentum"],
                    seed=SEED, deterministic=True, project=RUNS_DIR, name=runname,
                    exist_ok=True, verbose=False)
        trained[m["label"]] = dict(model=model, run=runname, **m, minutes=(time.time()-t0)/60)
        print(f"  selesai {trained[m['label']]['minutes']:.1f} mnt")
    except Exception as e:
        print("  ! gagal latih", m["label"], "->", e)
print("\nSelesai. Model terlatih:", list(trained.keys()))

===== yolo11m (tier m: imgsz=960 lr0=0.02 batch=2 epochs=100) =====
New https://pypi.org/project/ultralytics/8.4.75 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.152  Python-3.11.9 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32607MiB)
engine\trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=2, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=e:\CCTV\PIO\_pio_yolo\dataset.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=960, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.02, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11m.pt, momentum=0.9, mosaic=1.0, multi_scale=False, name=cmp_yolo11m, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=e:\CCTV\PIO\runs_compare, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=e:\CCTV\PIO\runs_compare\cmp_yolo11m, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    542720  ultralytics.nn.modules.block.C3k2            [1024, 256, 1, True]
 17                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 20                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]
 23        [16, 19, 22]  1   1411795  ultralytics.nn.modules.head.Detect           [1, [256, 512, 512]]
YOLO11m summary: 231 layers, 20,053,779 parameters, 20,053,763 gradients, 68.2 GFLOPs

Transferred 643/649 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.00.0 ms, read: 297.441.8 MB/s, size: 1069.0 KB)

train: Scanning E:\CCTV\PIO\_pio_yolo\labels\train... 1035 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1035/1035 [00:00<00:00, 1047.51it/s]

train: New cache created: E:\CCTV\PIO\_pio_yolo\labels\train.cache
val: Fast image access  (ping: 0.00.0 ms, read: 130.134.9 MB/s, size: 947.3 KB)

val: Scanning E:\CCTV\PIO\_pio_yolo\labels\val... 452 images, 0 backgrounds, 0 corrupt: 100%|██████████| 452/452 [00:00<00:00, 1092.93it/s]

val: New cache created: E:\CCTV\PIO\_pio_yolo\labels\val.cache

Plotting labels to e:\CCTV\PIO\runs_compare\cmp_yolo11m\labels.jpg...
optimizer: AdamW(lr=0.02, momentum=0.9) with parameter groups 106 weight(decay=0.0), 113 weight(decay=0.0005), 112 bias(decay=0.0)
Image sizes 960 train, 960 val
Using 8 dataloader workers
Logging results to e:\CCTV\PIO\runs_compare\cmp_yolo11m
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100      8.39G      1.418     0.9646      1.084        849        960: 100%|██████████| 518/518 [00:28<00:00, 18.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:04<00:00, 27.71it/s]

                   all        452      73859      0.869      0.747      0.826       0.55

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100      8.39G      1.398     0.8218      1.064        718        960: 100%|██████████| 518/518 [00:26<00:00, 19.34it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 28.44it/s]

                   all        452      73859       0.88      0.791      0.859       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100       8.4G      1.363     0.7842      1.059        599        960: 100%|██████████| 518/518 [00:26<00:00, 19.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:04<00:00, 27.53it/s]

                   all        452      73859      0.847       0.71      0.798      0.542

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100       8.4G      1.343     0.7888      1.059        278        960: 100%|██████████| 518/518 [00:26<00:00, 19.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.39it/s]

                   all        452      73859      0.892       0.77      0.853      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/100       8.4G      1.249     0.7059      1.015        639        960: 100%|██████████| 518/518 [00:26<00:00, 19.34it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.48it/s]

                   all        452      73859      0.919      0.817      0.886      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/100       8.4G      1.195     0.6675     0.9978        607        960: 100%|██████████| 518/518 [00:26<00:00, 19.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 28.74it/s]

                   all        452      73859      0.931      0.831      0.897      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/100       8.4G      1.139     0.6469     0.9778        343        960: 100%|██████████| 518/518 [00:26<00:00, 19.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.62it/s]

                   all        452      73859       0.93      0.833      0.898      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/100       8.4G      1.125     0.6342     0.9709        159        960: 100%|██████████| 518/518 [00:26<00:00, 19.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.61it/s]

                   all        452      73859       0.93      0.829      0.895       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/100       8.4G       1.15      0.604     0.9811        698        960: 100%|██████████| 518/518 [00:26<00:00, 19.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 28.78it/s]

                   all        452      73859       0.93      0.838      0.899      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/100       8.4G      1.126     0.6039     0.9798        471        960: 100%|██████████| 518/518 [00:26<00:00, 19.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 28.83it/s]

                   all        452      73859      0.929       0.84        0.9       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/100      9.76G       1.11      0.571     0.9659        553        960: 100%|██████████| 518/518 [00:27<00:00, 19.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.03it/s]

                   all        452      73859       0.94      0.849      0.906      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/100      9.76G      1.059     0.5471     0.9527        175        960: 100%|██████████| 518/518 [00:26<00:00, 19.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.03it/s]

                   all        452      73859      0.939      0.856       0.91      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/100      9.76G      1.078     0.5587     0.9529        670        960: 100%|██████████| 518/518 [00:26<00:00, 19.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.04it/s]

                   all        452      73859      0.937      0.843      0.903      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/100      9.76G      1.073     0.5502     0.9559         89        960: 100%|██████████| 518/518 [00:26<00:00, 19.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.26it/s]

                   all        452      73859      0.941      0.855      0.911      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/100      9.76G      1.043     0.5293     0.9448        516        960: 100%|██████████| 518/518 [00:26<00:00, 19.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 28.81it/s]

                   all        452      73859      0.945      0.867      0.915        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/100      9.76G      1.052     0.5226      0.946         68        960: 100%|██████████| 518/518 [00:26<00:00, 19.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.27it/s]

                   all        452      73859      0.936      0.854      0.908       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/100      9.76G      1.035     0.5292     0.9426        239        960: 100%|██████████| 518/518 [00:26<00:00, 19.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.31it/s]

                   all        452      73859      0.945      0.866      0.913      0.704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/100      9.76G      1.022      0.516     0.9396        227        960: 100%|██████████| 518/518 [00:27<00:00, 19.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.31it/s]

                   all        452      73859      0.948       0.87      0.918      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/100      9.76G      1.008     0.5064     0.9432        254        960: 100%|██████████| 518/518 [00:26<00:00, 19.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.51it/s]

                   all        452      73859      0.942      0.859      0.914      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/100      9.76G      1.013     0.4998      0.939        694        960: 100%|██████████| 518/518 [00:26<00:00, 19.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.10it/s]

                   all        452      73859      0.947       0.87      0.919      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/100      11.1G      1.001     0.4923     0.9306        349        960: 100%|██████████| 518/518 [00:26<00:00, 19.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.07it/s]

                   all        452      73859      0.948      0.871      0.921      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/100      11.1G      0.977     0.4924     0.9301        118        960: 100%|██████████| 518/518 [00:26<00:00, 19.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.74it/s]

                   all        452      73859      0.945      0.869      0.917       0.71

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/100      12.5G     0.9917     0.4919     0.9346        293        960: 100%|██████████| 518/518 [00:26<00:00, 19.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.67it/s]

                   all        452      73859      0.944      0.874      0.919      0.718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/100      12.5G     0.9864     0.4823     0.9299        319        960: 100%|██████████| 518/518 [00:26<00:00, 19.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.61it/s]

                   all        452      73859      0.945      0.866       0.92      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/100      12.5G     0.9796     0.4802     0.9311        404        960: 100%|██████████| 518/518 [00:26<00:00, 19.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.17it/s]

                   all        452      73859      0.947      0.874      0.921      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/100      12.5G     0.9926     0.4812      0.932        447        960: 100%|██████████| 518/518 [00:26<00:00, 19.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.13it/s]

                   all        452      73859      0.949      0.877      0.922      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/100      12.5G     0.9715     0.4716     0.9271        396        960: 100%|██████████| 518/518 [00:26<00:00, 19.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.07it/s]

                   all        452      73859      0.951      0.878      0.922      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/100      12.5G     0.9874     0.4733     0.9264        385        960: 100%|██████████| 518/518 [00:26<00:00, 19.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.72it/s]

                   all        452      73859      0.953      0.878      0.922      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/100      12.5G     0.9683       0.47      0.925        128        960: 100%|██████████| 518/518 [00:26<00:00, 19.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.93it/s]

                   all        452      73859       0.95      0.873      0.921      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/100      12.5G     0.9827     0.4713     0.9251        200        960: 100%|██████████| 518/518 [00:26<00:00, 19.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.58it/s]

                   all        452      73859      0.953      0.875      0.923      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/100      12.5G     0.9549     0.4595     0.9245        336        960: 100%|██████████| 518/518 [00:26<00:00, 19.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.06it/s]

                   all        452      73859      0.951      0.879      0.926      0.736

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/100      12.5G     0.9513     0.4566     0.9181        365        960: 100%|██████████| 518/518 [00:26<00:00, 19.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.70it/s]

                   all        452      73859      0.952      0.881      0.926      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/100      13.9G     0.9453     0.4547     0.9187        769        960: 100%|██████████| 518/518 [00:26<00:00, 19.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.66it/s]

                   all        452      73859      0.951      0.877      0.924      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/100      13.9G     0.9452     0.4534     0.9164        537        960: 100%|██████████| 518/518 [00:26<00:00, 19.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.09it/s]

                   all        452      73859      0.951      0.878      0.925      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/100      13.9G     0.9491     0.4558     0.9143        737        960: 100%|██████████| 518/518 [00:26<00:00, 19.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.51it/s]

                   all        452      73859      0.948      0.872      0.921      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/100      13.9G     0.9407     0.4515     0.9146       1097        960: 100%|██████████| 518/518 [00:26<00:00, 19.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.10it/s]

                   all        452      73859       0.95      0.879      0.925       0.71

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/100      13.9G     0.9492     0.4533     0.9182        290        960: 100%|██████████| 518/518 [00:26<00:00, 19.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.90it/s]

                   all        452      73859      0.952      0.881      0.925      0.733

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/100      13.9G     0.9311     0.4438     0.9145        754        960: 100%|██████████| 518/518 [00:26<00:00, 19.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.47it/s]

                   all        452      73859      0.954      0.882      0.926      0.738

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/100      13.9G     0.9426     0.4452      0.913        566        960: 100%|██████████| 518/518 [00:26<00:00, 19.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.08it/s]

                   all        452      73859      0.954      0.883      0.928      0.742

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/100      13.9G     0.9298     0.4404     0.9119        277        960: 100%|██████████| 518/518 [00:26<00:00, 19.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.59it/s]

                   all        452      73859      0.954      0.882      0.925      0.731

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/100      13.9G     0.9238     0.4431      0.916       1075        960: 100%|██████████| 518/518 [00:26<00:00, 19.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.33it/s]

                   all        452      73859      0.954      0.883       0.93      0.743

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/100      13.9G      0.938     0.4468      0.918        188        960: 100%|██████████| 518/518 [00:26<00:00, 19.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.74it/s]

                   all        452      73859      0.952      0.881      0.923      0.736

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/100      13.9G     0.9329     0.4412     0.9134         67        960: 100%|██████████| 518/518 [00:26<00:00, 19.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.67it/s]

                   all        452      73859      0.953      0.881      0.926      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/100      13.9G     0.9349     0.4433     0.9158        186        960: 100%|██████████| 518/518 [00:26<00:00, 19.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.85it/s]

                   all        452      73859      0.956      0.884      0.927      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/100      13.9G     0.9309     0.4416     0.9107        301        960: 100%|██████████| 518/518 [00:26<00:00, 19.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.36it/s]

                   all        452      73859      0.953      0.882      0.929      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/100      13.9G     0.9298     0.4409     0.9068        523        960: 100%|██████████| 518/518 [00:26<00:00, 19.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.49it/s]

                   all        452      73859      0.954      0.883      0.928      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/100      13.9G     0.9174     0.4324     0.9088        415        960: 100%|██████████| 518/518 [00:26<00:00, 19.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.26it/s]

                   all        452      73859      0.954      0.885      0.929      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/100      13.9G     0.9199     0.4314     0.9083        198        960: 100%|██████████| 518/518 [00:26<00:00, 19.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.83it/s]

                   all        452      73859      0.952      0.884      0.929      0.742

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/100      13.9G     0.9081      0.432      0.911        547        960: 100%|██████████| 518/518 [00:26<00:00, 19.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.90it/s]

                   all        452      73859      0.952      0.884      0.929      0.747

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/100      13.9G     0.9121     0.4304     0.9107        681        960: 100%|██████████| 518/518 [00:26<00:00, 19.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.56it/s]

                   all        452      73859      0.952      0.881      0.927      0.731

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/100      13.9G     0.9224     0.4326     0.9133        175        960: 100%|██████████| 518/518 [00:26<00:00, 19.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.51it/s]

                   all        452      73859      0.955      0.882      0.925      0.734

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/100      13.9G      0.905     0.4234     0.9029        175        960: 100%|██████████| 518/518 [00:26<00:00, 19.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.03it/s]

                   all        452      73859      0.956      0.883      0.928      0.744

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/100      13.9G     0.9098     0.4281     0.9082        564        960: 100%|██████████| 518/518 [00:26<00:00, 19.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.08it/s]

                   all        452      73859      0.955      0.884      0.927       0.74

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/100      13.9G     0.9127      0.431     0.9114        173        960: 100%|██████████| 518/518 [00:26<00:00, 19.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.98it/s]

                   all        452      73859      0.953      0.885      0.928      0.738

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/100      13.9G     0.9084      0.427     0.9087         96        960: 100%|██████████| 518/518 [00:26<00:00, 19.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.94it/s]

                   all        452      73859      0.957      0.883      0.928      0.746

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/100      13.9G     0.9025     0.4258     0.9073        267        960: 100%|██████████| 518/518 [00:26<00:00, 19.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.74it/s]

                   all        452      73859      0.956      0.884      0.931      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/100      13.9G     0.9215     0.4324     0.9093        653        960: 100%|██████████| 518/518 [00:26<00:00, 19.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.75it/s]

                   all        452      73859      0.956      0.884      0.932      0.751

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/100      13.9G     0.8934     0.4189     0.9067        289        960: 100%|██████████| 518/518 [00:26<00:00, 19.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.09it/s]

                   all        452      73859      0.956      0.885       0.93      0.751

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/100      13.9G     0.8906     0.4189     0.9035        470        960: 100%|██████████| 518/518 [00:26<00:00, 19.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.09it/s]

                   all        452      73859      0.953      0.886      0.929      0.746

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/100      13.9G     0.8988     0.4176     0.9061        748        960: 100%|██████████| 518/518 [00:26<00:00, 19.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.07it/s]

                   all        452      73859      0.956      0.887       0.93      0.749

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/100      15.4G     0.9026     0.4185     0.9014        599        960: 100%|██████████| 518/518 [00:26<00:00, 19.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.20it/s]

                   all        452      73859      0.955      0.887       0.93      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/100      15.4G     0.9111     0.4208     0.9051        314        960: 100%|██████████| 518/518 [00:26<00:00, 19.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.81it/s]

                   all        452      73859      0.956      0.886      0.927      0.743

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/100      15.4G     0.8933     0.4183     0.9054        715        960: 100%|██████████| 518/518 [00:26<00:00, 19.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.21it/s]

                   all        452      73859      0.957      0.885      0.932      0.751

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/100      15.4G     0.8995     0.4203     0.8988        257        960: 100%|██████████| 518/518 [00:26<00:00, 19.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.41it/s]

                   all        452      73859      0.958      0.885      0.931      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/100      15.4G      0.893     0.4158     0.9051        569        960: 100%|██████████| 518/518 [00:26<00:00, 19.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.34it/s]

                   all        452      73859      0.955      0.888       0.93      0.744

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/100      15.4G     0.8911     0.4108       0.91        220        960: 100%|██████████| 518/518 [00:26<00:00, 19.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.88it/s]

                   all        452      73859      0.958      0.887      0.932      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/100      15.4G     0.8753     0.4055     0.8956        442        960: 100%|██████████| 518/518 [00:26<00:00, 19.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.22it/s]

                   all        452      73859      0.956      0.886      0.932      0.755

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/100      16.8G     0.9002     0.4127      0.895        391        960: 100%|██████████| 518/518 [00:26<00:00, 19.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.24it/s]

                   all        452      73859      0.957      0.887      0.931      0.748

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/100      9.49G     0.8883     0.4077     0.8965        381        960: 100%|██████████| 518/518 [00:26<00:00, 19.36it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.99it/s]

                   all        452      73859      0.955      0.887      0.932      0.756

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/100      12.9G     0.8758     0.4038      0.898        222        960: 100%|██████████| 518/518 [00:26<00:00, 19.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.98it/s]

                   all        452      73859      0.958      0.886      0.932      0.754

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/100      12.9G     0.8694     0.4011     0.8972        279        960: 100%|██████████| 518/518 [00:26<00:00, 19.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.24it/s]

                   all        452      73859      0.959      0.886      0.933      0.756

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/100      12.9G     0.8921      0.406     0.8993        891        960: 100%|██████████| 518/518 [00:26<00:00, 19.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.11it/s]

                   all        452      73859      0.958      0.885      0.933      0.758

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/100      12.9G     0.8709     0.4034     0.8979        148        960: 100%|██████████| 518/518 [00:26<00:00, 19.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.10it/s]

                   all        452      73859      0.958      0.886      0.932      0.751

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/100      14.2G     0.8782     0.4068     0.8971        124        960: 100%|██████████| 518/518 [00:27<00:00, 18.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.02it/s]

                   all        452      73859      0.956      0.885      0.931      0.748

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/100      14.2G      0.875     0.4016      0.896        232        960: 100%|██████████| 518/518 [00:26<00:00, 19.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.48it/s]

                   all        452      73859      0.959      0.888      0.934      0.756

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/100        17G      0.871     0.3975     0.8942        715        960: 100%|██████████| 518/518 [00:26<00:00, 19.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.52it/s]

                   all        452      73859      0.958      0.887      0.932      0.751

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/100      9.95G     0.8658     0.3988     0.8936        497        960: 100%|██████████| 518/518 [00:26<00:00, 19.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.43it/s]

                   all        452      73859      0.958      0.887      0.932      0.755

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/100        11G     0.8576     0.3945     0.8954        807        960: 100%|██████████| 518/518 [00:26<00:00, 19.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.89it/s]

                   all        452      73859      0.959      0.886       0.93      0.751

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/100      12.3G     0.8702      0.396     0.8948        377        960: 100%|██████████| 518/518 [00:26<00:00, 19.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.49it/s]

                   all        452      73859      0.958      0.888      0.932      0.754

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/100      12.3G     0.8663     0.3974     0.8971        609        960: 100%|██████████| 518/518 [00:26<00:00, 19.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.19it/s]

                   all        452      73859      0.957      0.888      0.933      0.753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/100      12.3G     0.8583     0.3932     0.8933        210        960: 100%|██████████| 518/518 [00:26<00:00, 19.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.35it/s]

                   all        452      73859      0.957      0.888      0.933      0.757

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/100      12.3G      0.868     0.3936     0.8938         89        960: 100%|██████████| 518/518 [00:26<00:00, 19.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.10it/s]

                   all        452      73859      0.958      0.887      0.934      0.748

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/100      12.3G     0.8623     0.3909     0.8925        582        960: 100%|██████████| 518/518 [00:26<00:00, 19.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.32it/s]

                   all        452      73859      0.959      0.887      0.934      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/100      12.3G     0.8507     0.3855     0.8908       1089        960: 100%|██████████| 518/518 [00:26<00:00, 19.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.01it/s]

                   all        452      73859      0.959      0.887      0.933      0.756

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/100      12.3G      0.857      0.388     0.8918         93        960: 100%|██████████| 518/518 [00:26<00:00, 19.39it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.87it/s]

                   all        452      73859      0.959      0.887      0.934      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/100      12.3G      0.857     0.3893     0.8928         36        960: 100%|██████████| 518/518 [00:26<00:00, 19.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.13it/s]

                   all        452      73859      0.959      0.886      0.933      0.757

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/100      12.3G     0.8463      0.386     0.8912        175        960: 100%|██████████| 518/518 [00:26<00:00, 19.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.59it/s]

                   all        452      73859      0.958      0.888      0.933      0.757

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/100      13.6G     0.8582     0.3926     0.8947        220        960: 100%|██████████| 518/518 [00:26<00:00, 19.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.07it/s]

                   all        452      73859      0.959      0.887      0.933      0.753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/100      15.2G      0.858     0.3901     0.8944         70        960: 100%|██████████| 518/518 [00:26<00:00, 19.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.40it/s]

                   all        452      73859      0.959      0.889      0.934      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/100      15.2G      0.845     0.3809     0.8909        150        960: 100%|██████████| 518/518 [00:26<00:00, 19.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.92it/s]

                   all        452      73859      0.959      0.889      0.934      0.758

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/100      15.2G     0.8311     0.3767     0.8964         85        960: 100%|██████████| 518/518 [00:25<00:00, 20.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.64it/s]

                   all        452      73859      0.957      0.886      0.932      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/100      15.2G     0.8268     0.3727     0.8973         42        960: 100%|██████████| 518/518 [00:25<00:00, 20.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.56it/s]

                   all        452      73859      0.959      0.885      0.933      0.754

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/100      15.2G     0.8243     0.3712      0.896        556        960: 100%|██████████| 518/518 [00:25<00:00, 20.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.87it/s]

                   all        452      73859      0.958      0.889      0.935       0.76

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/100      15.2G     0.8221     0.3701     0.8999        572        960: 100%|██████████| 518/518 [00:24<00:00, 20.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.74it/s]

                   all        452      73859       0.96      0.888      0.935      0.763

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/100      15.2G     0.8177     0.3663     0.8964         39        960: 100%|██████████| 518/518 [00:24<00:00, 20.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.25it/s]

                   all        452      73859      0.959      0.888      0.934      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/100      15.2G     0.8216     0.3675     0.8987         90        960: 100%|██████████| 518/518 [00:24<00:00, 20.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.89it/s]

                   all        452      73859      0.958      0.888      0.935      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/100      15.2G     0.8101     0.3631     0.8967          2        960: 100%|██████████| 518/518 [00:24<00:00, 20.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.04it/s]

                   all        452      73859      0.958      0.888      0.935      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/100      15.2G     0.8103      0.363     0.8894        369        960: 100%|██████████| 518/518 [00:24<00:00, 20.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.94it/s]

                   all        452      73859      0.958      0.887      0.935      0.763

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/100      15.2G     0.8082      0.361     0.8929        583        960: 100%|██████████| 518/518 [00:24<00:00, 20.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 30.06it/s]

                   all        452      73859      0.959      0.887      0.936      0.762

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/100      15.2G     0.8076     0.3583     0.8894         58        960: 100%|██████████| 518/518 [00:24<00:00, 20.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:03<00:00, 29.95it/s]

                   all        452      73859       0.96      0.888      0.934       0.76

100 epochs completed in 0.879 hours.
Optimizer stripped from e:\CCTV\PIO\runs_compare\cmp_yolo11m\weights\last.pt, 40.5MB
Optimizer stripped from e:\CCTV\PIO\runs_compare\cmp_yolo11m\weights\best.pt, 40.5MB

Validating e:\CCTV\PIO\runs_compare\cmp_yolo11m\weights\best.pt...
Ultralytics 8.3.152  Python-3.11.9 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32607MiB)
YOLO11m summary (fused): 125 layers, 20,030,803 parameters, 0 gradients, 67.6 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 113/113 [00:04<00:00, 25.45it/s]

                   all        452      73859      0.958      0.888      0.935      0.763
Speed: 0.2ms preprocess, 2.0ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to e:\CCTV\PIO\runs_compare\cmp_yolo11m
  selesai 53.4 mnt

Selesai. Model terlatih: ['yolo11m']

## 4 · Hasil & pemenang

Evaluasi tiap model pada **val yang sama**, lalu bandingkan. Baris **PAPER-v10** = klaim Tabel 8 (referensi, 100 epoch). Sel menandai **model terbaik per tier** (berdasarkan mAP@50-95).

In [37]:
PAPER_T8 = {
 "yolov10n": dict(precision=0.938, recall=0.84, mAP50=0.90, mAP50_95=0.671),
 "yolov10s": dict(precision=0.954, recall=0.86, mAP50=0.92, mAP50_95=0.70),
 "yolov10m": dict(precision=0.961, recall=0.88, mAP50=0.97, mAP50_95=0.76),
}
def read_losses(run):
    csv=os.path.join(RUNS_DIR,run,"results.csv")
    if not os.path.exists(csv): return {}
    d=pd.read_csv(csv); d.columns=[c.strip() for c in d.columns]; last=d.iloc[-1]
    def pick(kind):
        cs=[c for c in d.columns if "val" in c.lower() and kind in c.lower()]
        for key in ("loss","om","oo"):
            for c in cs:
                if key in c.lower(): return float(last[c])
        return float(last[cs[0]]) if cs else float("nan")
    return dict(box_loss=pick("box"),cls_loss=pick("cls"),dfl_loss=pick("dfl"))

rows=[]
for label,info in trained.items():
    best=os.path.join(RUNS_DIR,info["run"],"weights","best.pt")
    mdl=YOLO(best) if os.path.exists(best) else info["model"]
    r=mdl.val(data=YAML_PATH,imgsz=TIER_CFG[info["tier"]]["imgsz"],split="val",verbose=False)
    rows.append(dict(model=label,tier=info["tier"],family=info["family"],
                     precision=round(float(r.box.mp),3),recall=round(float(r.box.mr),3),
                     mAP50=round(float(r.box.map50),3),mAP50_95=round(float(r.box.map),3),
                     **{k:round(v,3) for k,v in read_losses(info["run"]).items()}))
res=pd.DataFrame(rows)
if res.empty:
    print("Belum ada model terlatih.")
else:
    res=res.sort_values(["tier","mAP50_95"],ascending=[True,False]).reset_index(drop=True)
    display(res)
    out=os.path.join(RUNS_DIR,"comparison_results.csv"); res.to_csv(out,index=False); print("Disimpan ke Drive:",out)

Ultralytics 8.3.152  Python-3.11.9 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32607MiB)
YOLO11m summary (fused): 125 layers, 20,030,803 parameters, 0 gradients, 67.6 GFLOPs
val: Fast image access  (ping: 0.00.0 ms, read: 3117.7879.6 MB/s, size: 1034.3 KB)

val: Scanning E:\CCTV\PIO\_pio_yolo\labels\val.cache... 452 images, 0 backgrounds, 0 corrupt: 100%|██████████| 452/452 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 29/29 [00:07<00:00,  4.03it/s]

                   all        452      73859      0.958      0.888      0.935      0.766
Speed: 0.2ms preprocess, 3.0ms inference, 0.0ms loss, 7.0ms postprocess per image
Results saved to runs\detect\val7

,model,tier,family,precision,recall,mAP50,mAP50_95,box_loss,cls_loss,dfl_loss
0,yolo11m,m,yolo11,0.958,0.888,0.935,0.766,0.785,0.351,0.918

Disimpan ke Drive: e:\CCTV\PIO\runs_compare\comparison_results.csv

In [38]:
# Pemenang per tier + selisih vs baseline YOLOv10 tier sama
if not res.empty:
    for tier in sorted(res.tier.unique()):
        sub=res[res.tier==tier].sort_values("mAP50_95",ascending=False)
        win=sub.iloc[0]
        base=sub[sub.family=="yolov10"]
        bm=float(base.iloc[0]["mAP50_95"]) if not base.empty else float("nan")
        print(f"\n### TIER {tier.upper()} — pemenang: {win['model']}  (mAP50-95={win['mAP50_95']}, mAP50={win['mAP50']})")
        if not base.empty:
            d=win['mAP50_95']-bm
            verdict="MENGALAHKAN" if d>0 else ("SERI dengan" if abs(d)<1e-9 else "kalah dari")
            print(f"    vs YOLOv10{tier} (baseline, mAP50-95={bm}): {win['model']} {verdict} baseline (Δ={d:+.3f})")
        print(sub[['model','precision','recall','mAP50','mAP50_95']].to_string(index=False))

### TIER M — pemenang: yolo11m  (mAP50-95=0.766, mAP50=0.935)
  model  precision  recall  mAP50  mAP50_95
yolo11m      0.958   0.888  0.935     0.766

In [39]:
# Grafik batang mAP50-95 per tier
import matplotlib.pyplot as plt
if not res.empty:
    tiers=sorted(res.tier.unique()); fig,axes=plt.subplots(1,len(tiers),figsize=(6*len(tiers),4.5),squeeze=False)
    for ax,tier in zip(axes[0],tiers):
        sub=res[res.tier==tier].sort_values("mAP50_95")
        colors=["#d95f02" if f=="yolov10" else "#1b9e77" for f in sub.family]
        ax.barh(sub.model,sub.mAP50_95,color=colors)
        for y,(v,p) in enumerate(zip(sub.mAP50_95,sub.mAP50)): ax.text(v,y,f" {v:.3f}",va="center",fontsize=8)
        ax.set_title(f"Tier {tier} — mAP@50-95 (oranye=YOLOv10 baseline)"); ax.set_xlabel("mAP@50-95")
    plt.tight_layout(); plt.savefig(os.path.join(RUNS_DIR,"comparison_mAP.png"),dpi=130); plt.show()

## 5 · Kesimpulan

- Pemenang aktual ditentukan oleh tabel & grafik di atas (pada **epoch yang kamu pilih**).
- Ekspektasi umum pada epoch sama: **YOLO11 ≥ YOLOv10**, **YOLOv12** sering tertinggi pada scene padat (tapi paling berat), **YOLOv9** kompetitif, **YOLOv8** biasanya baseline terendah.
- Semua dilatih dengan **resep identik per tier (Tabel 7)** tanpa tuning per-model → adu murni arsitektur. Bila ingin lebih jujur lagi untuk satu arsitektur, lakukan tuning lr/optimizer khusus model itu.
- **Catatan QUICK_TEST.** Bila `QUICK_TEST=True` (3 epoch), peringkat sudah indikatif tetapi angka belum final. Untuk klaim skripsi, naikkan epoch (idealnya 100) — jalankan bertahap per tier agar muat di Colab.

Output tersimpan di Drive: `runs_compare/comparison_results.csv` & `comparison_mAP.png`.

In [40]:
# ===== Model baru (Drive) vs KLAIM PAPER Tabel 8 =====
import os, glob, pandas as pd
RUNS_DIR = str(BASE / "runs_compare")
RUNS_DIR = "/content/drive/MyDrive/PIO/runs_compare"   # ganti bila beda

# Klaim paper (Tabel 8) — 100 epoch
PAPER_T8 = {
 "yolov10n": dict(box_loss=2.1, cls_loss=0.9, dfl_loss=1.95, precision=0.938, recall=0.84, mAP50=0.90, mAP50_95=0.671),
 "yolov10s": dict(box_loss=1.9, cls_loss=0.8, dfl_loss=1.90, precision=0.954, recall=0.86, mAP50=0.92, mAP50_95=0.70),
 "yolov10m": dict(box_loss=1.6, cls_loss=0.6, dfl_loss=1.75, precision=0.961, recall=0.88, mAP50=0.97, mAP50_95=0.76),
}
METRICS = ["box_loss","cls_loss","dfl_loss","precision","recall","mAP50","mAP50_95"]

def read_results_row(rd):
    csv=os.path.join(rd,"results.csv")
    if not os.path.exists(csv): return None
    d=pd.read_csv(csv); d.columns=[c.strip() for c in d.columns]
    mcol=[c for c in d.columns if ("map50-95" in c.lower()) or ("map50_95" in c.lower())]
    row=d.loc[d[mcol[0]].idxmax()] if mcol else d.iloc[-1]
    def col(p):
        cs=[c for c in d.columns if p(c.lower())]; return float(row[cs[0]]) if cs else float("nan")
    def loss(k):
        cs=[c for c in d.columns if "val" in c.lower() and k in c.lower()]
        for key in ("loss","om","oo"):
            for c in cs:
                if key in c.lower(): return float(row[c])
        return float(row[cs[0]]) if cs else float("nan")
    return dict(box_loss=loss("box"), cls_loss=loss("cls"), dfl_loss=loss("dfl"),
                precision=col(lambda c:"precision" in c), recall=col(lambda c:"recall" in c),
                mAP50=col(lambda c:("map50" in c) and ("95" not in c)),
                mAP50_95=col(lambda c:("map50-95" in c) or ("map50_95" in c)))

# baca reproduksi dari Drive
repro={}
for rd in sorted(glob.glob(os.path.join(RUNS_DIR,"cmp_*"))):
    r=read_results_row(rd)
    if r: repro[os.path.basename(rd)[4:]]=r

# tabel gabungan: kolom = klaim paper + reproduksimu
cols={}
for k in ["yolov10n","yolov10s","yolov10m"]:
    cols[f"PAPER {k}"]=[round(PAPER_T8[k][m],3) for m in METRICS]
for label in sorted(repro):
    cols[f"repro {label}"]=[round(repro[label].get(m,float('nan')),3) for m in METRICS]
table=pd.DataFrame(cols, index=METRICS)
print("=== Reproduksi (3 epoch) vs KLAIM PAPER (100 epoch) ===");
try: display(table)
except NameError: print(table.to_string())

# verdict tiap model-m: vs paper yolov10m (TAK adil: 3 vs 100 ep) & vs repro yolov10m (adil: epoch sama)
base_paper = PAPER_T8["yolov10m"]["mAP50_95"]
base_repro = repro.get("yolov10m",{}).get("mAP50_95", float("nan"))
print(f"\nBaseline mAP50-95 -> PAPER yolov10m={base_paper} (100ep) | REPRO yolov10m={round(base_repro,3) if base_repro==base_repro else 'NA'} (3ep)")
for label in sorted(repro):
    if not label.endswith("m"): continue
    v=repro[label]["mAP50_95"]
    dp=v-base_paper; dr=(v-base_repro) if base_repro==base_repro else float("nan")
    fair = "MENANG" if dr>0 else ("seri" if abs(dr)<1e-9 else "kalah")
    print(f"  {label:9} mAP50-95={v:.3f} | vs PAPER(100ep) Δ={dp:+.3f} | vs REPRO yolov10m(3ep, ADIL) Δ={dr:+.3f} -> {fair}")

=== Reproduksi (3 epoch) vs KLAIM PAPER (100 epoch) ===

           PAPER yolov10n  PAPER yolov10s  PAPER yolov10m
box_loss            2.100           1.900           1.600
cls_loss            0.900           0.800           0.600
dfl_loss            1.950           1.900           1.750
precision           0.938           0.954           0.961
recall              0.840           0.860           0.880
mAP50               0.900           0.920           0.970
mAP50_95            0.671           0.700           0.760

Baseline mAP50-95 -> PAPER yolov10m=0.76 (100ep) | REPRO yolov10m=NA (3ep)